export const SkillsOptions = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'Backend',
  'Frontend',
  'Fullstack',
  'ReactJS',
  'VueJS',
  'Docker',
  'NextJS',
  'Angular',
  'SASS',
  'LESS',
  'TailwindCSS',
  'Bootstrap',
  'NodeJS',
  'ExpressJS',
  'NestJS',
  'PHP',
  'Laravel',
  'Ruby on Rails',
  'Django',
  'Spring Boot',
  'ASP.NET',
  'React Native',
  'Flutter',
  'Swift',
  'Kotlin',
  'Java (Android)',
  'Objective-C',
  'AWS',
  'Google Cloud Platform',
  'Docker',
  'CI/CD',
  'GitLab CI',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Oracle',
  'SQL Server',
  'SQLite',
  'Python',
  'Data Science',
  'Machine Learning',
  'Selenium',
];

// export const experienceOptions = ['Intern', 'Fresher', 'Junior', 'Mid-level', 'Senior', 'Lead'];

export const experienceOptions = [
  'Intern Developer',
  'Fresher Developer',
  'Junior Developer',
  'Middle Developer',
  'Senior Developer',
  'Lead Developer',
  'Principal Engineer',
  'Software Architect',
  'Technical Manager',
  'Director of Engineering',
  'VP of Engineering',
  'Chief Technology Officer (CTO)',
];
