export const SkillsOptions = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'ReactJS',
  'VueJS',
  'Angular',
  'SASS',
  'LESS',
  'TailwindCSS',
  'Bootstrap', 
  'NodeJS',
  'ExpressJS',
  'NestJS',
  'PHP',
  'Laravel',
  'Ruby on Rails',
  'Django',
  'Spring Boot',
  'ASP.NET',
  'React Native',
  'Flutter',
  'Swift',
  'Kotlin',
  'Java (Android)',
  'Objective-C',
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Jenkins',
  'GitLab CI', 
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Oracle',
  'SQL Server',
  'SQLite', 
  'Cybersecurity',
  'Penetration Testing',
  'Ethical Hacking',
  'OWASP', 
  'Python',
  'R',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Data Science',
  'Machine Learning', 
  'Solidity',
  'Web3.js',
  'Ethereum',
  'Smart Contracts', 
  'Selenium',
  'JUnit',
  'TestNG',
  'Mocha',
  'Chai',
  'Jest',
  'Cypress', 
];

export const experienceOptions = ['Intern', 'Fresher', 'Junior', 'Mid-level', 'Senior', 'Lead'];
