export const SkillsOptions = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'Backend',
  'Frontend',
  'Fullstack',
  'ReactJS',
  'VueJS',
  'Docker',
  'NextJS',
  'Angular',
  'SASS',
  'LESS',
  'TailwindCSS',
  'Bootstrap',
  'NodeJS',
  'ExpressJS',
  'NestJS',
  'PHP',
  'Laravel',
  'Django',
  'Spring Boot',
  'React Native',
  'Flutter',
  'Swift',
  'Kotlin',
  'AWS',
  'Docker',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Oracle',
  'SQLite',
  'Python',
  'Selenium',
];

export const experienceOptions = [
  'Intern Developer',
  'Fresher Developer',
  'Junior Developer',
  'Middle Developer',
  'Senior Developer',
  'Lead Developer',
  'Principal Engineer',
  'Software Architect',
  'Technical Manager',
  'Director of Engineering',
  'VP of Engineering',
  'Chief Technology Officer (CTO)',
];

export const GenderOptions = ['Nam', 'Nữ'];

export const WorkForm = ['Full-time', 'Part-time', 'Remote', 'Hybrid', 'Freelance', 'Contract-based', 'On-site'];

export const Status = ['Active', 'Inactive'];
